# ------------------------------------------------------------------------------
# _config.yml
# ------------------------------------------------------------------------------
#
# This config file is meant for settings that affect the whole site.
#
# Once the site is live it's expected that you won't be changing this.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ------------------------------------------------------------------------------
# Site settings
# Feel free to make adjustments here.
# ------------------------------------------------------------------------------

# This title should be short enough to fit on a single line on a mobile phone
# The site title appears in several different places and distinguishes your
# website from others'. For maximum informational content, titles of the form:
# "[region] Quakers" or "Quakers in [region]" are recommended.
# Long/Formal names can be used in the description and on the home page where
# there is more space.

title: Cambridgeshire Quakers

# An email address to appear in the site footer.

email: info@cambridgeshire-quakers.org.uk

description: > # this angle-bracket means to treat newlines in this block as spaces
  Cambridgeshire Area Quaker Meeting brings together Friends from Local Meetings
  in Cambridge, Ely, Huntingdon, Peterborough, St Neots and Wisbech. We are part
  of Britain Yearly Meeting of the Religious Society of Friends (Quakers).

url: "http://cambridgeshire-quakers.org.uk" # the base hostname & protocol for your site

baseurl: "" # the subpath of your site, e.g. /blog.

noindex: true

# ------------------------------------------------------------------------------
# Build settings
# This ensures all the nuts and bolts in the site fit together nicely.
# ------------------------------------------------------------------------------

# set the markdown parser
markdown: kramdown

# Set the directory which should be considered the base directory
# by the sass preprocessor
sass:
  sass_dir: /ext-lib/bootstrap-sass/assets/stylesheets/

# Declare that we are interested in items in the future
# (i.e. events not blog posts)
future: true

# collections
#
# Each collection is a set of documents accessible site-wide
#
# We're going to be doing some particularly funky things with the meetings, so
# don't remove that one.

collections:
  meetings:
    name: Meetings
    output: true
  concerns:
    name: Concerns
    output: true
  rooms:
    name: Rooms
    output: false
  events:
    name: Events
    output: true

# defaults
#
# This applies default values to groups of documents

defaults:
  -
    scope:
      type: pages
    values:
      layout: page
  -
    scope:
      type: meetings
    values:
      layout: meeting
      regularMeetings:
        - Sundays 1030-1130
  -
    scope:
      type: concerns
    values:
      layout: page
  -
    scope:
      type: events
    values:
      layout: event


# fallbacks
#
# This is used in _includes/accessor to infer values for similar keys
# where it is a bad idea to assume the key will always be populated.
#
# The structure of each item in the array is:
#
#   - preferredName
#   - alternativeName
#   - someOtherName
#   ...

fallbacks:
  -
    - shortTitle
    - title
    - name
  -
    - title
    - shortTitle
    - name
  -
    - startDate
    - date
